# Generated by Django 3.0.7 on 2021-04-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='myuser',
            name='items_of_interest',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='myuser',
            name='job',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
